version: "3.3"
services: 

#  busybox:
 #   build:
  #    context: busybox
  #  image: busybox-volumes
  #  container_name: busybox
  #  volumes: 
  #    - ./../www:/var/www/html
  
  php:
    build:
      context: php
    image: php-local
    container_name: php
    volumes: 
      - ./../www:/var/www/html
    networks: 
      - internal
    ports:
      - 9000:9000

  nginx:
    build:
      context: nginx
    image: nginx-local
    container_name: nginx
    volumes:
      - ./../www:/var/www/html
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - internal
    ports:
      - 80:80
networks: 
  internal:
    
    
